### ISSUE TITLE
PWA 使用问题。 

### ISSUE THREAD

**Issue by liwan11123123** [YDJ-FE/ts-react-webpack#15]
修改接口，sw.js 默认会缓存上一次的接口，修改页面也是

**Comment by jackple** [comment]
@liwan11123123 现在可以了, 合并代码后你可以把sw卸载, 我的本次修改就是本地环境不使用offline-plugin了
![image](https://user-images.githubusercontent.com/6183232/50543532-e78af180-0c15-11e9-8618-da11dc6d61c5.png)
