### ISSUE TITLE
可否添加单元测试？ 

### ISSUE THREAD

**Issue by liwan11123123** [YDJ-FE/ts-react-webpack#16]
当代码写到一定量的时候，我遇到了一些很奇怪的问题，语法通过，但是运行报错，代码是之前写的代码，并没有做改动，然后修复它，之后又有其他地方出现bug， 于是觉得单元测试很有必要集成进来， 减少二次修改带来的额外测试负担

**Comment by jackple** [comment]
提个pr?

**Comment by liwan11123123** [comment]
我试试
