### ISSUE TITLE
npm run dev  报错

### ISSUE THREAD

**Issue by WaveStill** [YDJ-FE/ts-react-webpack#19]
npm i 之后，什么也没改动，npm run dev 就报错了
ERROR in ./src/containers/shared/App/index.tsx 34:11
Module parse failed: Unexpected token (34:11)
You may need an appropriate loader to handle this file type.
| var Home = Loadable({
|   loader: function loader() {
>     return import(
|     /* webpackChunkName: "home" */
|     '@views/Home');
 @ ./src/index.tsx 15:0-36 30:7-16
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/index.tsx

**Comment by jackple** [comment]
@WaveStill 请检查安装的webpack版本，你可以把它锁死
