### ISSUE TITLE
How easily could Ant Design could be replaced by Ant Design Pro?

### ISSUE THREAD

**Issue by vcardins** [YDJ-FE/ts-react-webpack#20]

**Comment by jackple** [comment]
Ant Design Pro is an integrated fe system, I do not want to use it in this project.
https://pro.ant.design/docs/getting-started

**Comment by vcardins** [comment]
Thanks for the response, but actually I asked about the effort necessary to apply ant design pro, didn't ask or suggest to be used in this project. Yeah, I'll do my homework!! Thanks

**Comment by jackple** [comment]
@vcardins Actually，I did not use ant design pro before！so！😄😄
