### ISSUE TITLE
替换mobx-react，使用mobx-react-lite？

### ISSUE THREAD

**Issue by liwan11123123** [YDJ-FE/ts-react-webpack#21]
能够有个分支， 替换mobx-react，使用mobx-react-lite？

**Comment by jackple** [comment]
> 能够有个分支， 替换mobx-react，使用mobx-react-lite？

正在调研中

**Comment by jackple** [comment]
@liwan11123123 

[范例](https://github.com/YDJ-FE/ts-react-webpack/blob/master/src/containers/views/Login/index.tsx)

mobx-react-lite的应用场景, 暂时只感觉到以下两点是真正要用到的
1. 用React的hooks不能使用mobx-react的observer, 而要使用mobx-react-lite的observer
2. 使用mobx-react-lite的useComputed

也欢迎你的建议或评论
