### ISSUE TITLE
Asset size exceeds the recommended limit

### ISSUE THREAD

**Issue by pcegarra** [YDJ-FE/ts-react-webpack#22]
Hi, thanks for this boilerplate, Im using it in all my react projects.

I have a doubt, When I execute the build for production Im getting the following message:
```
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (2.23 MiB)
      static/js/manifest.afa9dd1218acd8b9e0e9.js
      static/css/split-vendor.0.d0eb07cce6a0bc77d6a7.css
      static/js/split-vendor.0.496b6c66170658a3896e.js
      static/css/app.1.cb78b99e0d79844339ad.css
      static/js/app.1.79d4b602a734eb46094a.js
```

The split-vendor.js size is 2.1MB.

How can I reduce the size of this file? Thanks

**Comment by jackple** [comment]
@pcegarra I think I had made a mistake about choosing echarts for a boilerplate. If you don't need it, just wipe it out.😄😄
In addition, you can run `npm run build:qa --report` to get information of your build.
![image](https://user-images.githubusercontent.com/6183232/56777129-5a8e2880-6802-11e9-8157-bd1fb2aa650b.png)
