### ISSUE TITLE
Add intl

### ISSUE THREAD

**Issue by pcegarra** [YDJ-FE/ts-react-webpack#23]
I think that any good starter requires i18n

**Comment by jackple** [comment]
it's a good recommendation, I will think about it!

**Comment by pcegarra** [comment]
Im trying to integrate this in the boilerplate
https://github.com/akameco/babel-plugin-react-intl-auto/tree/master/examples/with-typescript

But Im getting problems running the script:
 UnhandledPromiseRejectionWarning: SyntaxError ... PageLoading/index.scss.d.ts: Unexpected reserved word 'interface'

**Comment by jackple** [comment]
[feat/intl](https://github.com/YDJ-FE/ts-react-webpack/tree/feat/intl)
I have created a new branch for this, can you make a pr?

**Comment by pcegarra** [comment]
Done, check the pr
https://github.com/YDJ-FE/ts-react-webpack/pull/25/commits/27fef64ffabbb166bde221a3df5bfd08b956cceb

To try it just change the state to 'es' in the LanguageProvider component, we probably need to create a store to handle this

**Comment by jackple** [comment]
@pcegarra https://github.com/YDJ-FE/ts-react-webpack/pull/25#issuecomment-489497322

I'm getting some test result before merge

**Comment by pcegarra** [comment]
Nice, what about https://ant.design/components/locale-provider/?

**Comment by jackple** [comment]
@pcegarra yeah, I'm using `LocaleProvider` in my company project.

**Comment by pcegarra** [comment]
Do you plan to add it in feat/react-intl-universal?

**Comment by jackple** [comment]
@pcegarra yes

**Comment by jackple** [comment]
@pcegarra https://github.com/YDJ-FE/ts-react-webpack/commit/bdecb146dd2cdb476215cd97f6b8201fd20d6d3b
