### ISSUE TITLE
RrouterStore not working using createBrowserHistory

### ISSUE THREAD

**Issue by pcegarra** [YDJ-FE/ts-react-webpack#24]
Hi, I know that this issue is not problem from this repo, but maybe you know why im getting the following problem:

I changed the Provider element to use createBrowserHistory instead createHashHistory, but when I use routerStore.push('/') the url in the browser changes, but the view nots.

Any idea? thanks!

**Comment by jackple** [comment]
@pcegarra I did not use createBrowserHistory for a long time. I try to find some docs, and it should help. 

https://github.com/alisd23/mobx-react-router#troubleshooting

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md
