### ISSUE TITLE
css-modules-typescript-loader!.

### ISSUE THREAD

**Issue by william-xue** [YDJ-FE/ts-react-webpack#27]
ERROR in ./src/index.scss (./node_modules/cache-loader/dist/cjs.js??ref--5-1!./node_modules/css-modules-typescript-loader!./node_modules/css-loader??ref--5-3!./node_modules/postcss-loader/src!./node_modules/sass-loader/lib/loader.js??ref--5-5!./src/index.scss)
Module build failed (from ./node_modules/css-modules-typescript-loader/index.js):
Error: No exported locals found for /Users/xueyuan/Desktop/Denv/ts/ts-react-webpack/src/index.scss

**Comment by jackple** [comment]
@william-xue 试试锁死`css-modules-typescript-loader`到2.0.0

**Comment by jackple** [comment]
https://github.com/seek-oss/css-modules-typescript-loader/pull/16
