### ISSUE TITLE
运行起来  怎么连api   或者配api

### ISSUE THREAD

**Issue by TrumpUSA** [YDJ-FE/ts-react-webpack#29]
{
"code": 10001,
"data": "token过期",
"flag": 0,
"msg": "error_token"
}

做后端的。。。。   这个咋用。谢谢

**Comment by TrumpUSA** [comment]
在哪配 服务地址 。。。

**Comment by jackple** [comment]
@TrumpUSA build/env.json

**Comment by TrumpUSA** [comment]
@  http://localhost:8080/ 之后直接 {
"code": 10001,
"data": "token过期",
"flag": 0,
"msg": "error_token"
}

怎么打开登陆的地方。

**Comment by TrumpUSA** [comment]
http://localhost:8080/login   用这个也是 token 过期。。
