### ISSUE TITLE
react-loadable依赖的react版本太老

### ISSUE THREAD

**Issue by songning0605** [YDJ-FE/ts-react-webpack#38]
现在有一个问题，`react-loadable` 依赖的版本是16.0.0，项目依赖高于 `16.8.6` 会提示下边的错误
`react-dom.development.js?5729:12357 Warning: componentWillMount has been renamed, and is not recommended for use`，请问版主是怎么解决的

**Comment by jackple** [comment]
我会把`react-loadable`去掉
